all:
  vars:
    ansible_user: user 
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null user@51.250.65.61"
    
    zabbix_server_ip: 192.168.10.29
        # Добавляем хосты для мониторинга
    zabbix_hosts: 
      - name: web-1.ru-central1.internal
        ip: 192.168.20.24
      - name: web-2.ru-central1.internal
        ip: 192.168.30.15
      - name: elastic.ru-central1.internal
        ip: 192.168.20.20
      - name: kibana.ru-central1.internal
        ip: 192.168.10.30 
    elastic_server_ip: 192.168.20.20

  children:
    bastion:
      hosts:
        bastion.ru-central1.external:
          ansible_host: "51.250.65.61"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    webservers:
      hosts:
        web-1.ru-central1.internal:
          ansible_host: "192.168.20.24"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        web-2.ru-central1.internal:
          ansible_host: "192.168.30.15"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"

    elastic:
      hosts:
        elastic.ru-central1.internal:
          ansible_host: "192.168.20.20"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"



 #   zabbix:
 #     hosts:
 #       zabbix.ru-central1.external:
 #         ansible_host: "158.160.110.156"
       
    zabbix:
      hosts:
        zabbix.ru-central1.internal:
          ansible_host: "192.168.10.29"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
          zabbix_admin_user: "Admin"
          zabbix_admin_password: "zabbix"
          zabbix_discovery_name: "Network Discovery"
          zabbix_discovery_iprange: "192.168.0.0/16,192.168.10.0/24,192.168.20.0/24,192.168.30.0/24"
          zabbix_discovery_delay: "10m"
          zabbix_action_name: "Auto Register Linux Hosts"

    kibana:
      hosts:
        kibana.ru-central1.internal:
          ansible_host: "192.168.10.30"
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
