all:
  vars:
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -J user@158.160.113.140

  children:
    bastion:
      hosts:
        bastion.ru-central1.internal:
          ansible_host: "158.160.113.140"
          ansible_ssh_common_args: ""

    webservers:
      hosts:
        web-1.ru-central1.internal:
          ansible_host: "192.168.20.10"
        web-2.ru-central1.internal:
          ansible_host: "192.168.30.34"

    elastic:
      hosts:
        elastic.ru-central1.internal:
          ansible_host: "192.168.20.21"

    zabbix:
      hosts:
        zabbix.ru-central1.internal:
          ansible_host: "192.168.10.4"

    kibana:
      hosts:
        kibana.ru-central1.internal:
          ansible_host: "192.168.10.34"
