- name: Настроим Веб-сервер
  hosts: webservers
  become: yes
  pre_tasks:
    - name: Удалить старый файл репозитория Docker
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Удалить старый ключ Docker
      file:
        path: /etc/apt/keyrings/docker.asc
        state: absent

    - name: Обновить кеш пакетов после очистки
      apt:
        update_cache: yes
      ignore_errors: yes  # Если кэш всё ещё сломан, продолжим

  roles:
    - nginx
    - zabbix-agent
    - filebeat
  vars:
    zabbix_server_ip: "zabbix.ru-central1.internal"
    elasticsearch_host: "elastic.ru-central1.internal:9200"