- name: Configure Zabbix Server
  hosts: zabbix
  become: yes
  vars:
    zabbix_db_host: localhost
    zabbix_db_name: zabbix
    zabbix_db_user: zabbix
    zabbix_db_password: zabbix
  roles:
    - zabbix-server