---
- name: Reload systemd
  command: systemctl daemon-reload

- name: Restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: Restart postgresql
  systemd:
    name: postgresql
    state: restarted

- name: disable apache2
  service:
    name: apache2
    state: disable

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Restart zabbix-agent
  systemd:
    name: zabbix-agent
    state: restarted