#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOxAJ9lQnCS5JnQrSrV5PpbAMGxoODP0VzQhRewbrJtn art@debian-test-CLEAN

  - name: admin
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    lock_passwd: false
    passwd: "$6$rounds=4096$wPs2z7VqC9$X6q5h7W8pY2rT3sV1qZ9mN0bC4dF7gH2jK5lP8oR6tS9uY4vAxE3zB1cM6nDf"

ssh_pwauth: true
disable_root: false
chpasswd:
  list: |
    admin:123456
  expire: false

runcmd:
  # Разрешаем весь трафик внутри VPC
  - iptables -I INPUT -s 192.168.10.0/24 -j ACCEPT
  - iptables -I INPUT -s 192.168.20.0/24 -j ACCEPT
  - iptables -I INPUT -s 192.168.30.0/24 -j ACCEPT
  - iptables-save > /etc/iptables/rules.v4