---
- name: Скачать пакет релиза Zabbix
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu18.04_all.deb
    dest: /tmp/zabbix-release_6.0-4+ubuntu18.04_all.deb
    mode: '0644'

- name: Установить пакет релиза Zabbix
  shell: dpkg -i /tmp/zabbix-release_6.0-4+ubuntu18.04_all.deb
  ignore_errors: yes

- name: Убедиться что репозиторий Zabbix 6.0 настроен
  lineinfile:
    path: /etc/apt/sources.list.d/zabbix.list
    regexp: '^deb https://repo\.zabbix\.com/zabbix/'
    line: 'deb https://repo.zabbix.com/zabbix/6.0/ubuntu bionic main'
    backup: yes

- name: Обновить кэш apt
  shell: apt update -y

- name: Установить необходимые пакеты включая zabbix-sql-scripts
  shell: apt install -y postgresql zabbix-server-pgsql zabbix-frontend-php zabbix-nginx-conf zabbix-agent zabbix-sql-scripts php7.2-pgsql php7.2-mbstring php7.2-gd php7.2-xml php7.2-bcmath

- name: Создать PID директорию для Zabbix
  file:
    path: /run/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Создать директорию логов для Zabbix
  file:
    path: /var/log/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Убедиться что PostgreSQL запущен
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Проверить существует ли база данных Zabbix
  shell: sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -w "{{ zabbix_db_name }}" | wc -l
  register: db_exists
  changed_when: false

- name: Создать базу данных PostgreSQL для Zabbix
  shell: sudo -u postgres createdb "{{ zabbix_db_name }}"
  when: db_exists.stdout == "0"
  ignore_errors: yes

- name: Проверить существует ли пользователь Zabbix
  shell: sudo -u postgres psql -t -c "SELECT COUNT(*) FROM pg_roles WHERE rolname='{{ zabbix_db_user }}';"
  register: user_exists
  changed_when: false

- name: Создать пользователя PostgreSQL для Zabbix
  shell: sudo -u postgres psql -c "CREATE USER {{ zabbix_db_user }} WITH PASSWORD '{{ zabbix_db_password }}'"
  when: user_exists.stdout.strip() == "0"
  ignore_errors: yes

- name: Выдать привилегии на базу данных пользователю Zabbix
  shell: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ zabbix_db_name }} TO {{ zabbix_db_user }};"
  ignore_errors: yes

- name: Импортировать схему базы данных Zabbix (Zabbix 6.0)
  shell: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql -d zabbix
  args:
    executable: /bin/bash

- name: Настроить Zabbix сервер
  template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
  notify: Restart zabbix-agent

- name: Настроить Nginx для Zabbix
  template:
    src: nginx.conf.j2
    dest: /etc/zabbix/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

- name: Создать симлинк сайта для Nginx
  file:
    src: /etc/zabbix/nginx.conf
    dest: /etc/nginx/sites-enabled/zabbix
    state: link
  notify: Restart nginx

- name: Настроить веб-интерфейс Zabbix
  template:
    src: zabbix.conf.php.j2
    dest: /usr/share/zabbix/conf/zabbix.conf.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Удалить сайт по умолчанию Nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Удалить конфликтующий zabbix.conf если существует
  file:
    path: /etc/nginx/conf.d/zabbix.conf
    state: absent
  notify: Restart nginx

- name: Остановить и отключить Apache2
  shell: systemctl stop apache2 && systemctl disable apache2
  ignore_errors: yes

- name: Включить и запустить Zabbix сервер
  systemd:
    name: zabbix-server
    enabled: yes
    state: started

- name: Включить и запустить PHP-FPM
  systemd:
    name: php7.2-fpm
    enabled: yes
    state: started

- name: Включить и запустить Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Включить и запустить Zabbix агент
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started