- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Run Elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    state: started
    restart_policy: always
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

- name: Wait for Elasticsearch to start
  wait_for:
    port: 9200
    delay: 10
    state: started